### PR TITLE
BAGS in Installer gvim_8.0.1071_x86

### PR DESCRIPTION
**Pull request by a-kubik**
hi!
Please add to *.bat file
for example vim80\vimtutor.bat 
change 
vim -u NONE -c "so $VIMRUNTIME/tutor/tutor.vim"
to
call vim -u NONE -c "so $VIMRUNTIME/tutor/tutor.vim"
because now second string (vim -u NONE -c "set nocp" %TUTORCOPY%) newer run

[call - return to back *.bat file in point of call and continue run on  this *.bat]
max deep is 8 call

and two:

if checked "Create .bat files for command line use" without "Vim executables and runtime files" the *.bat files in SystemRoot don't create, why?

### CODE REVIEW

**Comment by chrisbra** [comment]
I am not sure I understand. Can you please squash your changes into a single commit? What exact problem are you trying to fix? BTW: I think youre changes should actually be better applied to the vim repository and this one is the wrong place for it.

**Comment by k-takata** [comment]
@a-kubik I don't understand why you create a PR instead of an issue.
Actually this is not a right place to report issues of Vim installer. This repository was a test bench for vim/vim-win32-installer.
When creating vim/vim-win32-installer, we should have transferred the ownership of this repository to the vim organization instead of cloning it. But it is too late to do so.

**Comment by k-takata** [comment]
For the first problem, it should be reported to [vim/vim](https://github.com/vim/vim).
For the second problem, unchecking "Vim executables and runtime files" is nonsense. The item should not be able to be unchecked, I think. I will create a patch later.

**Comment by k-takata** [comment]
Created two PRs: vim/vim#2105, vim/vim#2106.

**Pull request closed without merging**
